### ISSUE TITLE
ERROR! 'yum' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by GitAvinashreddy** [networktocode/ntc-ansible#129]
Being new to `Git` this is my first issue/question on Ansible.  I have started learning & tried to create a play which installs a package on the host listed in the host file.

```
# ansible-playbook sam.yaml
ERROR! 'yum' is not a valid attribute for a Play

The error appears to have been in '/etc/ansible/sam.yaml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  tasks:
- name: install
  ^ here
```

**`sam.yml` file output** There might be something here which I have missed.
```
---
- hosts: [mainserver]
  remote_user: root
  become: yes
  tasks:
- name: install
  yum: name=httpd state=present
```

**Comment by GitAvinashreddy** [comment]
Its very strange I don't know why but this below solution worked.  below is the modified file which worked 100% without any error.

```
---
- hosts: [mainserver]
  remote_user: root
  become: yes
  tasks:
        - name: install apache
          yum: name=httpd state=present
```

I just added <kbd>tab</kbd> to last 2 line and apache to the second last line.
