### ISSUE TITLE
Problem with connection to cisco/hp switches

### ISSUE THREAD

**Issue by sqrteh** [networktocode/ntc-ansible#132]
Hi,

I am trying to make connection with my hp/cisco switches by using ntc modules but always i get some kind of errors. I have no idea what am i doing wrong. Below i present my configurations and output of errors. I was testing this on ansible with version 2.3.0 and 1.9.4 and always i get an error.

testbook.yml:

```
- name: HP testing
  hosts: hp
  tasks:
   - name: GET DATA
     ntc_show_command:
        connection: ssh
        platform: "{{ platform }}"
        command: show version
        host: "{{ ansible_ssh_host }}"
        username: "{{ ansible_ssh_user }}"
        password: "{{ ansible_ssh_pass }}"
```
...

hosts:
```

[hp]
switch1

[hp:vars]
platform = hp_procurve
ansible_ssh_user=user
ansible_ssh_pass=pass
ansible_ssh_host=10.167.156.216

```
---

output after commands: ansible-playbook -vvvv -i hosts testbook.yml
```

PLAYBOOK: testbook.yml *********************************************************
1 plays in testbook.yml

PLAY [HP testing] **************************************************************

TASK [setup] *******************************************************************
Using module file /home/as/tmp/ansible/lib/ansible/modules/core/system/setup.py
<10.167.156.216> ESTABLISH CONNECTION FOR USER: user on PORT 22 TO 10.167.156.216
<10.167.156.216> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1476480494.44-205322436109200 `" && echo ansible-tmp-1476480494.44-205322436109200="` echo $HOME/.ansible/tmp/ansible-tmp-1476480494.44-205322436109200 `" ) && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/as/tmp/ansible/lib/ansible/executor/task_executor.py", line 122, in run
    res = self._execute()
  File "/home/as/tmp/ansible/lib/ansible/executor/task_executor.py", line 488, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/as/tmp/ansible/lib/ansible/plugins/action/normal.py", line 33, in run
    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))
  File "/home/as/tmp/ansible/lib/ansible/plugins/action/__init__.py", line 573, in _execute_module
    tmp = self._make_tmp_path(remote_user)
  File "/home/as/tmp/ansible/lib/ansible/plugins/action/__init__.py", line 221, in _make_tmp_path
    result = self._low_level_execute_command(cmd, sudoable=False)
  File "/home/as/tmp/ansible/lib/ansible/plugins/action/__init__.py", line 727, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/home/as/tmp/ansible/lib/ansible/plugins/connection/paramiko_ssh.py", line 284, in exec_command
    chan.exec_command(cmd)
  File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 60, in _check
    return func(self, *args, **kwds)
  File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 234, in exec_command
    self._wait_for_event()
  File "build/bdist.linux-x86_64/egg/paramiko/channel.py", line 1109, in _wait_for_event
    raise e
SSHException: Channel closed.

fatal: [switch1]: FAILED! => {
    "failed": true, 
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
	to retry, use: --limit @/home/X/testbook.retry

PLAY RECAP *********************************************************************
switch1          : ok=0    changed=0    unreachable=0    failed=1   
```

-----

Thanks for any kind of help.

**Comment by jedelman8** [comment]
Can you please show your full playbook?

**Comment by sqrteh** [comment]
I didnt create nothing more because even that simple example doesn't work properly - for hp switches that is all.

**Comment by jedelman8** [comment]
But it's important to see the full playbook to help. 

Can you please ensure gather_facts is set to no and connection is set to local in your play definition?

**Comment by sqrteh** [comment]
my playbook with everythings options. 

hp_playbook.yml
```
---
- name: HP testing
  hosts: hp
  connection: local
  gather_facts: no
  tasks:
   - name: GET DATA
     ntc_show_command:
        connection: netmiko_ssh
        platform: "{{ platform }}"
        command: show version
        host: "{{ ansible_ssh_host }}"
        username: "{{ ansible_ssh_user }}"
        password: "{{ ansible_ssh_pass }}"
...

```

cisco_playbook.yml

```

---
- name: Cisco testing
  hosts: cisco
  connection: local
  gather_facts: no
  tasks:
   - name: GET DATA
     ntc_show_command:
        connection: netmiko_ssh
        platform: "{{ platform }}"
        command: show version
        host: "{{ ansible_ssh_host }}"
        username: "{{ ansible_ssh_user }}"
        password: "{{ ansible_ssh_pass }}"
...

```


When i execute playbook with changed options connection to local, and gather_facts to no i have right now a little bit other output like this:

**#: ansible-playbook -vvvv hp_playbook.yml**
```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /home/as/tmp/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: hp_playbook.yml ******************************************************
1 plays in hp_playbook.yml

PLAY [HP testing] **************************************************************

TASK [GET DATA] ****************************************************************
task path: /home/as/hp_playbook.yml:7
Using module file /home/as/tmp/ntc-ansible/library/ntc_show_command.py
<10.167.156.216> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.167.156.216> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1476911209.22-88462373694876 `" && echo ansible-tmp-1476911209.22-88462373694876="` echo $HOME/.ansible/tmp/ansible-tmp-1476911209.22-88462373$
<10.167.156.216> PUT /tmp/tmpQzaRLb TO /root/.ansible/tmp/ansible-tmp-1476911209.22-88462373694876/ntc_show_command.py
<10.167.156.216> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1476911209.22-88462373694876/ /root/.ansible/tmp/ansible-tmp-1476911209.22-88462373694876/ntc_show_command.py && sleep 0'
<10.167.156.216> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1476911209.22-88462373694876/ntc_show_command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1476911209.22-88462373694876/" > /dev/null 2>&1 && sleep 0'
fatal: [irs2-3.7.net.onet]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "command": "show version",
            "connection": "netmiko_ssh",
            "delay": "1",
            "file": null,
            "host": "10.167.156.216",
            "index_file": "index",
            "key_file": null,
            "local_file": null,
            "optional_args": {},
            "password": "xxxxx",
            "platform": "hp_procurve",
            "port": "22",
            "secret": null,
            "template_dir": "ntc-templates/templates",
            "trigger_device_list": null,
            "use_keys": false,
            "use_templates": true,
            "username": "username"
        },
        "module_name": "ntc_show_command"
    },
    "msg": "could not find or read index file"
}
        to retry, use: --limit @/home/as/hp_playbook.retry

PLAY RECAP *********************************************************************
switch1          : ok=0    changed=0    unreachable=0    failed=1

```

**"msg": "could not find or read index file"** - the same output is when i execute playbook for hp and cisco switches.

**Comment by sqrteh** [comment]
I create some other playbook with diffrent module of ntc - like this:

```
--
- name: HP testing
  hosts: hp
  connection: local
  tasks:
   - name: GET DATA
     ntc_get_facts:
        connection: netmiko_ssh
        platform: "{{ platform }}"
        host: "{{ ansible_ssh_host }}"
        username: "{{ ansible_ssh_user }}"
        password: "{{ ansible_ssh_pass }}"

```

i get output error like this:

```

Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /home/as/tmp/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: testv2.yml ************************************************************
1 plays in testv2.yml

PLAY [HP testing] **************************************************************

TASK [setup] *******************************************************************
Using module file /home/as/tmp/netmiko/setup.py
fatal: [switch1]: FAILED! => {
    "failed": true, 
    "msg": "module (setup) is missing interpreter line"
}
	to retry, use: --limit @/home/as/testv2.retry

PLAY RECAP *********************************************************************
switch1          : ok=0    changed=0    unreachable=0    failed=1   


```

**Comment by sqrteh** [comment]
Ok i solved problem.

Everything what i needed was add direct path to template_dir in my playbook.

```
---
- name: Cisco testing
  hosts: cisco
  connection: local
  gather_facts: no
  tasks:
   - name: GET DATA
     ntc_show_command:
        connection: netmiko_ssh
        platform: "{{ platform }}"
        command: 'show version | inc uptime'
        host: "{{ ansible_ssh_host }}"
        username: "{{ ansible_ssh_user }}"
        password: "{{ ansible_ssh_pass }}"
        use_templates: True
        template_dir: /home/as/tmp/ntc-ansible/ntc-templates/templates/
```

---

I have one more question yet, is there any possibillities to use module like ntc_show_command with pipes ? add something like this in playbook : command: 'show version | inc uptime' ? 
Thanks for answer.

**Comment by GGabriele** [comment]
Glad it is working now. 

Regarding your question, unfortunately that's not possible.

**Comment by nncse** [comment]
Hi, am new here. I was wondering if somebody could help me out. I am also seeing the problem "msg": "could not find or read index file". Although I have  tried to directly point the index file in the yaml file but to no avail. Below is my entire error message and yaml file. 

Thanks in advance.

TASK [GET LLDP NEIGHBORS] ******************************************************
task path: /home/user/ansible-files/ntc-ansible/ntc-templates/templates/auto-config-port-descriptions.yaml:16
Using module file /home/user/ansible-files/ntc-ansible/library/ntc_show_command.py
<c3548> ESTABLISH LOCAL CONNECTION FOR USER: root
<c3548> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550 `" && echo ansible-tmp-1480704963.75-150827960692550="` echo $HOME/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550 `" ) && sleep 0'
<c3548> PUT /tmp/tmpqGzeVA TO /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ntc_show_command.py
<c3548> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ntc_show_command.py && sleep 0'
<c3548> EXEC /bin/sh -c '/usr/bin/python /home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/ntc_show_command.py; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1480704963.75-150827960692550/" > /dev/null 2>&1 && sleep 0'
fatal: [c3548]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "command": "show lldp neighbors", 
            "connection": "ssh", 
            "delay": "1", 
            "file": null, 
            "host": "c3548", 
            "index_file": "/home/user/ansible-files/ntc-ansible/ntc_templates/templates", 
            "key_file": null, 
            "local_file": null, 
            "optional_args": {}, 
            "password": "xxxxxxxx", 
            "platform": "cisco_nxos", 
            "port": "22", 
            "secret": null, 
            "template_dir": "/home/user/ansible-files/ntc-ansible/ntc_templates/templates", 
            "trigger_device_list": null, 
            "use_keys": false, 
            "use_templates": true, 
            "username": "admin"
        }, 
        "module_name": "ntc_show_command"
    }, 
    "msg": "could not find or read index file"
}
	to retry, use: --limit @/home/user/ansible-files/ntc-ansible/ntc-templates/templates/auto-config-port-descriptions.retry

PLAY RECAP *********************************************************************
c3548                      : ok=1    changed=0    unreachable=0    failed=1   



YAML FILE:
=======

     - name: GET LLDP NEIGHBORS
        ntc_show_command:
          connection: ssh
          platform: cisco_nxos
          index_file: /home/user/ansible-files/ntc-ansible/ntc_templates/templates
          template_dir: /home/user/ansible-files/ntc-ansible/ntc_templates/templates
          command: 'show lldp neighbors'
          host: "{{ inventory_hostname }}"
          username: 'admin'
          password: 'xxxxxxx'
          use_templates: True
        register: neighbors
        tags: neighbors

**Comment by haind13** [comment]
I have same error...

**Comment by nncse** [comment]
haind13,

I am not sure if your issue is resolved. Feel free to drop a comment again.

**Comment by sqrteh** [comment]
Hi again,

I think you have problem right there:
`index_file: /home/user/ansible-files/ntc-ansible/ntc_templates/templates`

You have to change this directly to proper file for index_file, that mean for example smth like this:
`index_file: /home/user/ansible-files/ntc-ansible/ntc_templates/templates/hp_procurve_show_version.conf`

But without index_file it should works too, if you correctly configure index_file in templade directory.

**Comment by GGabriele** [comment]
@haind13 @nncse Hi guys, @sqrteh  is right. `index_file` points to the index file itself, not the directory where it resides.

From documentation:

```
    index_file:
        description:
            - name of index file.  file location must be relative to
              the template_dir
        required: false
        default: index
```
