### ISSUE TITLE
Commands sent that require response throws exception

### ISSUE THREAD

**Issue by nerdofthenetwork** [networktocode/ntc-ansible#157]
I'm trying to zeroize the crypto keys on IOS devices and recreate them. IOS prompts the below. At the prompt I want to enter "yes". At first glance I think I need to modify the base_connection.py script from netmiko, but maybe I'm wrong. Is the module able to handle prompts in an "expect" like manner? 

% All keys will be removed.
% All router certs issued using these keys will also be removed.
Do you really want to remove these keys? [yes/no]:

Error - An exception occurred during task execution. To see the full traceback, use -vvv. The error was: netmiko.ssh_exception.NetMikoTimeoutException: Timed-out reading channel, data not available.

**Comment by jasonbarbee** [comment]
Make sure there is not a force option on zeroing the keys... but if it helps  - I ran into this type of issue with file prompts and saving to hit yes or not. Very different, but you might find a workaround like I did. The issue may be in PyNTC library (another related repo). As a workaround I modified my local PyNTC to send a few commands like this using the native.send_command_timing - which does not require a response and can extend the time that netmiko looks for the prompt again. Then I used it again to respond - in my case pressing enter, then the find_prompt presses enter and looks for a prompt to reset its state. 
           self.native.send_command_timing('show running-config')
            self.native.send_command_timing('\n',delay_factor=10)
            self.native.find_prompt()

**Comment by itdependsnetworks** [comment]
@nerdofthenetwork carriage return `\r` should work. e.g. this worked for me:

```
    - ntc_config_command:
        provider: "{{ ios_provider }}"
        commands:
          - "do erase startup-config\r"
```

**Comment by nerdofthenetwork** [comment]
@itdependsnetworks that works! thanks!

```
- name: Remove/generate new crypto keys
     ntc_config_command:
       connection: ssh
       platform: cisco_ios_ssh
       commands:
       - "crypto key zeroize rsa\ryes\r"
```
