### ISSUE TITLE
keep SSH/Telnet sessions during loop

### ISSUE THREAD

**Issue by vaneuk** [networktocode/ntc-ansible#176]
Hello,
I've got following task:

```
    - name: Run show ip arp vrf xxx
      ntc_show_command:
        command: "show ip arp vrf {{ item.vrf_name }}"
        <...>
      with_items: "{{ show_vrf_result.response }}"
```
      
I see that ansible creates new ssh/telnet session for each looped command. This approach significantly slows down command collection. It would be great to have an option to keep ssh/telnet sessions with devices during loop.

thanks!
