### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by dbarreda** [networktocode/ntc-ansible#219]
Getting this trace back when I execute something. Seems netmiko and ntc are doing some nested encode? I have put the example below as well.

Thanks!

```
fatal: [server.my.domain]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_q5k4eZ/ansible_module_ntc_get_facts.py\", line 293, in <module>\n    main()\n  File \"/tmp/ansible_q5k4eZ/ansible_module_ntc_get_facts.py\", line 284, in main\n    device = ntc_device(device_type, host, username, password, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pyntc-0.0.6-py2.7.egg/pyntc/__init__.py\", line 35, in ntc_device\n    return device_class(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pyntc-0.0.6-py2.7.egg/pyntc/devices/ios_device.py\", line 39, in __init__\n    self.open()\n  File \"/usr/lib/python2.7/site-packages/pyntc-0.0.6-py2.7.egg/pyntc/devices/ios_device.py\", line 55, in open\n    verbose=False)\n  File \"/usr/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py\", line 190, in ConnectHandler\n    return ConnectionClass(*args, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/netmiko/base_connection.py\", line 245, in __init__\n    self.establish_connection()\n  File \"/usr/lib/python2.7/site-packages/netmiko/base_connection.py\", line 742, in establish_connection\n    device_type=self.device_type, ip=self.host, port=self.port)\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

Did some test over python console and I'm getting the same 

```
# python
Python 2.7.5 (default, May 31 2018, 09:41:32)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> u'ñ'
u'\xf1'
>>> u'ñ'.encode('utf8')
'\xc3\xb1'
>>> u'ñ'.encode('utf8').encode('utf8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

Locale on global settings at server it's
```
#  locale
LANG=en_US.UTF-8
LC_CTYPE=
LC_NUMERIC=
LC_TIME=
LC_COLLATE=
LC_MONETARY=
LC_MESSAGES=
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by dbarreda** [comment]
This is the playbook that throws that error
```
---
- hosts: ios
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable
  ignore_errors: no

  tasks:
  - name: NTC Get Facts
    ntc_get_facts:
      platform: cisco_ios_ssh
      host: “{{ ansible_host }}”
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
```
