### ISSUE TITLE
errors running ntc_file_copy

### ISSUE THREAD

**Issue by bgoulet00** [networktocode/ntc-ansible#238]
i'm receiving errors that I don't understand. 

TASK [COPYING IMAGE TO DEVICE FLASH] ********************************************************************************************************************************************************************************************************
task path: /home/bgoulet/projects/ios-upgrade2.yml:28
<192.168.100.2> ESTABLISH LOCAL CONNECTION FOR USER: bgoulet
<192.168.100.2> EXEC /bin/sh -c 'echo ~bgoulet && sleep 0'
<192.168.100.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023 `" && echo ansible-tmp-1550690322.34-44660806874023="` echo /home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023 `" ) && sleep 0'
Using module file /home/bgoulet/.ansible/plugins/modules/ntc-ansible/library/ntc_file_copy.py
<192.168.100.2> PUT /home/bgoulet/.ansible/tmp/ansible-local-25844jQJSUs/tmp3b4Ipn TO /home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/AnsiballZ_ntc_file_copy.py
<192.168.100.2> EXEC /bin/sh -c 'chmod u+x /home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/ /home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/AnsiballZ_ntc_file_copy.py && sleep 0'
<192.168.100.2> EXEC /bin/sh -c '/usr/bin/python /home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/AnsiballZ_ntc_file_copy.py && sleep 0'
<192.168.100.2> EXEC /bin/sh -c 'rm -f -r /home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/AnsiballZ_ntc_file_copy.py", line 113, in <module>
    _ansiballz_main()
  File "/home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/AnsiballZ_ntc_file_copy.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/bgoulet/.ansible/tmp/ansible-tmp-1550690322.34-44660806874023/AnsiballZ_ntc_file_copy.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_ntc_file_copy_payload_DazkZU/__main__.py", line 329, in <module>
  File "/tmp/ansible_ntc_file_copy_payload_DazkZU/__main__.py", line 270, in main
  File "/home/bgoulet/.local/lib/python2.7/site-packages/pyntc/__init__.py", line 38, in ntc_device
    return device_class(*args, **kwargs)
  File "/home/bgoulet/.local/lib/python2.7/site-packages/pyntc/devices/ios_device.py", line 42, in __init__
    self.open()
  File "/home/bgoulet/.local/lib/python2.7/site-packages/pyntc/devices/ios_device.py", line 300, in open
    verbose=False,
  File "/home/bgoulet/.local/lib/python2.7/site-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/home/bgoulet/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/home/bgoulet/.local/lib/python2.7/site-packages/netmiko/base_connection.py", line 786, in establish_connection
    device_type=self.device_type, ip=self.host, port=self.port)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1

This is my playbook:
```
- name: upgrade ios device
  hosts: all
  connection: local
  
  vars:
    new_image: "./ test.txt"
    version: "12.2(44)Sc"
    ios_provider:
      username: "admin"
      password: "xxxxxx"
      platform: "cisco_ios_ssh"
      connection: ssh
      file_system: "flash:"

    
  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:
  
    - name: COPYING IMAGE TO DEVICE FLASH
      ntc_file_copy:
        local_file: "{{ new_image }}"
        host: “{{ inventory_hostname }}”
        provider: "{{ ios_provider }}"
      when: ansible_net_version != version
```
